name: ProBending
version: ${project.version}
main: com.probending.probending.ProBending
api-version: 1.13
depend: [ProjectKorra, ProtocolLib, PlaceholderAPI, WorldEdit]
softdepend: [Multiverse-Core]
authors: [DomiRusz24]
permissions:
  probending:
    command:
      arena:
        default: op
      arenaconfig:
        default: op
      probending:
        default: op
      leave:
        default: op
      pblevel:
        default: op
      forcestart:
        default: op
      team:
        default: op




